# Generated by Django 3.2 on 2023-04-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Токен пользователя'),
        ),
    ]
