# Generated by Django 3.2 on 2023-04-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20230421_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(blank=True, to='reviews.Genre'),
        ),
    ]
